name: Check for Consistency and Correctness

on:
  push:
    branches-ignore:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  update_build_test:
    name: Update, Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          # The prefix cache key, this can be changed to start a new cache manually.
          prefix-key: "rust-cache-v0.1"

      - name: Update
        uses: actions-rs/cargo@v1
        with: 
          command: update
      - name: Build and run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  
  format:
    name: Formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          cache: false
      - name: Run formatter
        uses: actions-rust-lang/rustfmt@v1